In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [19]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [20]:
## Define the vocabulary size
voc_size=10000

In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[983, 7742, 5070, 1226],
 [983, 7742, 5070, 7545],
 [983, 7622, 5070, 1250],
 [5434, 1209, 9376, 1373, 2413],
 [5434, 1209, 9376, 1373, 2274],
 [9761, 983, 5589, 5070, 1472],
 [9716, 9098, 9567, 1373]]

In [23]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  983 7742 5070 1226]
 [   0    0    0    0  983 7742 5070 7545]
 [   0    0    0    0  983 7622 5070 1250]
 [   0    0    0 5434 1209 9376 1373 2413]
 [   0    0    0 5434 1209 9376 1373 2274]
 [   0    0    0 9761  983 5589 5070 1472]
 [   0    0    0    0 9716 9098 9567 1373]]


In [26]:
## feature representation
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [29]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 75ms/step


array([[[ 0.04784509, -0.04345458, -0.00322441,  0.00873753,
         -0.01192739,  0.03781796,  0.03678239,  0.04025016,
          0.01228466, -0.03016903],
        [ 0.04784509, -0.04345458, -0.00322441,  0.00873753,
         -0.01192739,  0.03781796,  0.03678239,  0.04025016,
          0.01228466, -0.03016903],
        [ 0.04784509, -0.04345458, -0.00322441,  0.00873753,
         -0.01192739,  0.03781796,  0.03678239,  0.04025016,
          0.01228466, -0.03016903],
        [ 0.04784509, -0.04345458, -0.00322441,  0.00873753,
         -0.01192739,  0.03781796,  0.03678239,  0.04025016,
          0.01228466, -0.03016903],
        [-0.01108068,  0.00552947, -0.02126323,  0.03349513,
          0.02279471, -0.02416556, -0.04843614, -0.02963625,
         -0.0210359 , -0.01029509],
        [ 0.01201519,  0.04112268,  0.04708233,  0.02708698,
         -0.0183174 , -0.03683322, -0.0229077 ,  0.03073836,
          0.0411948 , -0.00454583],
        [-0.01844811,  0.04820389, -0.03723494,  0.0

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0,  983, 7742, 5070, 1226], dtype=int32)

In [31]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 63ms/step


array([[ 0.04784509, -0.04345458, -0.00322441,  0.00873753, -0.01192739,
         0.03781796,  0.03678239,  0.04025016,  0.01228466, -0.03016903],
       [ 0.04784509, -0.04345458, -0.00322441,  0.00873753, -0.01192739,
         0.03781796,  0.03678239,  0.04025016,  0.01228466, -0.03016903],
       [ 0.04784509, -0.04345458, -0.00322441,  0.00873753, -0.01192739,
         0.03781796,  0.03678239,  0.04025016,  0.01228466, -0.03016903],
       [ 0.04784509, -0.04345458, -0.00322441,  0.00873753, -0.01192739,
         0.03781796,  0.03678239,  0.04025016,  0.01228466, -0.03016903],
       [-0.01108068,  0.00552947, -0.02126323,  0.03349513,  0.02279471,
        -0.02416556, -0.04843614, -0.02963625, -0.0210359 , -0.01029509],
       [ 0.01201519,  0.04112268,  0.04708233,  0.02708698, -0.0183174 ,
        -0.03683322, -0.0229077 ,  0.03073836,  0.0411948 , -0.00454583],
       [-0.01844811,  0.04820389, -0.03723494,  0.04848036, -0.0155521 ,
         0.04718485, -0.03835224, -0.0309553 